/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.*;
import javax.swing.JFrame;

public class ViewMostraPessoas extends javax.swing.JFrame {
    
    private ctrlVendedor objctrlVendedor;
    private ctrlCorretor objctrlCorretor;
    private ctrlComprador objctrlComprador;
    
    public ViewMostraPessoas(ctrlVendedor ctrlVendedor, ctrlCorretor ctrlCorretor, ctrlComprador ctrlComprador) {
        this.objctrlVendedor = ctrlVendedor;
        this.objctrlCorretor = ctrlCorretor;
        this.objctrlComprador = ctrlComprador;
        initComponents();
        

        String saida = "Vendedores cadastrados: ";
        for(Vendedor v : ctrlVendedor.getListaVendedor()){
            if(v instanceof Vendedor){

                saida+= "\nNome: " + v.getNome() + "\nTipo: Vendedor\nCPF: " + v.getCpf() + "\nEmail: "+ v.getEmail() +"   Fone: "+ v.getFone();
            }
        }
        
        saida+="\n\n\nCorretores cadastrados: ";
        for(Corretor cor : ctrlCorretor.getListaCorretor()){
            if(cor instanceof Corretor){
                saida+= "\nNome: " + cor.getNome() + "\nTipo: Corretor\nCPF: " + cor.getCpf() + "\nEmail: "+ cor.getEmail() +"   Fone: "+ cor.getFone();
            }
        }
        
        saida+="\n\n\nCompradores cadastrados: ";
        for(Comprador comp : ctrlComprador.getListaComprador()){
            if(comp instanceof Comprador){
                saida+= "\nNome: " + comp.getNome() + "\nTipo: Comprador\nCPF: " + comp.getCpf() + "\nEmail: "+ comp.getEmail() +"   Fone: "+ comp.getFone();
            }
            
            saida+="\n\n";
        }
        
        jTextArea1.setText(saida);
        this.setTitle("Cadastros");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
